Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -19,13 +19,30 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.10'  # Указываем версию Python
+          python-version: '3.9'  # Указываем версию Python
 
       - name: Install dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk
           pip install buildozer cython
+
+      - name: Set up Android SDK
+        run: |
+          mkdir -p ~/.android
+          touch ~/.android/repositories.cfg
+          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -O /tmp/android-sdk.zip
+          unzip /tmp/android-sdk.zip -d ~/.android
+          export ANDROID_HOME=~/.android
+          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/tools/bin
+          yes | sdkmanager --licenses
+
+          # Устанавливаем build-tools и platform-tools
+          sdkmanager "build-tools;30.0.3" "platform-tools" "platforms;android-30"
+
+          # Явно проверяем наличие AIDL
+          $ANDROID_HOME/build-tools/30.0.3/aidl --version || echo "AIDL not found, installing..."
+          export PATH=$PATH:$ANDROID_HOME/build-tools/30.0.3
 
       - name: Run Buildozer
         run: |
